version: 2.1
parameters:
  task:
    type: string
    default: default
orbs:
  node: circleci/node@4.7
jobs:
  test:
    docker:
      - image: circleci/node:16.13
    description: 'Test the script'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn validate
  sync:
    docker:
      - image: circleci/node:16.13
    description: 'Sync the database'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn sync
workflows:
  validate:
    when:
      and:
        - equal: [default, << pipeline.parameters.task >>]
        - not:
            matches:
              pattern: '^main$'
              value: << pipeline.git.branch >>
    jobs:
      - test
  sync:
    when:
      and:
        - equal: [sync, << pipeline.parameters.task >>]
        - equal: [main, << pipeline.git.branch >>]
    jobs:
      - sync
